include:
  - path: ../common/docker-compose.common.yml
    env_file:
        - ../env-files/.env.${ENV:?error}

services:
  wordpress-dev:
    image: wordpress:6.6.2
    container_name: ${ENV:?error}_wordpress_dev
    # links:
    #   - ${ENV:?error}_mysql
    volumes:
      - wordpress_dev_data:/var/www/html # Full wordpress project
    networks:
      - public
      - internal
    ports:
      - ${EXPOSED_PORT:?error}:80
    env_file:
      - ../env-files/.env.${ENV}
      - ../env-files/wordpress-dev.env.${ENV}

volumes:
  wordpress_dev_data:
